service: ${self:custom.metadata-spreadsheet-tools.name}

frameworkVersion: ">=1.0.0 <2.0.0"

plugins:
  - serverless-python-requirements

custom:
  metadata-spreadsheet-tools: ${file(metadata-spreadsheet-tools.yml)}

provider:
  name: aws
  runtime: python3.6
  region: us-east-1

functions:
  generate:
    handler: handler.generate
    events:
      - http:
          path: generate
          method: post
          cors: true